doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            artefact_id: Cbase\ArtefactGuide\Infrastructure\Persistence\Doctrine\ArtefactIdType
            image_id: Cbase\ArtefactGuide\Infrastructure\Persistence\Doctrine\ImageIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ArtefactGuide:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/ArtefactGuide/Domain'
                prefix: 'Cbase\ArtefactGuide\Domain'
                alias: 'ArtefactGuideDomain'

            Shared:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shared/Domain'
                prefix: 'Cbase\Shared\Domain'
                alias: 'SharedDomain'