security:

    providers:
        oauth:
            id: Cbase\Authentication\Infrastructure\OAuth2\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        auth:
            pattern: ^/api/auth/callback
            context: api_context # need to put auth and api into same context to have api guarded
            custom_authenticators:
                - Cbase\Authentication\Infrastructure\OAuth2\Authenticator
        api:
            pattern: ^/api
            methods: [PUT, POST, DELETE]
            context: api_context
            custom_authenticators:
                - Cbase\Authentication\Infrastructure\OAuth2\Authenticator
        main:
            pattern: ^/
            context: api_context
            lazy: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/api/auth, roles: PUBLIC_ACCESS }
         - { path: ^/api, roles: ROLE_USER }
