sudo: required
language: php
php: '7.2'

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    on_success: never

jobs:
  fast_finish: true
  include:

  - stage: test
    env: JOB=test
    install: make api-install-dependencies
    script: make api-ci

  - stage: build-tag
    if: tag =~ ^\d+\.\d+\.\d+$
    env: JOB=deploy VERSION=$TRAVIS_TAG
    install: make install
    script: make docker-tag-push

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/
