sudo: required
language: php
php: '7.2'

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    on_success: never

before_install:
  # we use our own postgresql container
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose -f docker-compose.staging.yml pull
  - make docker-up-stage

jobs:
  fast_finish: true
  include:

  - stage: pre-test
    env: JOB=test
    script: curl http://localhost:8080

  - stage: test
    env: JOB=test
    install: make install
    script: make test-security

  - stage: test
    env: JOB=test
    install: make install
    script: make test

  - stage: test
    env: JOB=test
    install: make install
    script: make test-static

  - stage: test
    env: JOB=test
    install: make install
    script: make test-style

  - stage: build-tag
    if: tag =~ ^\d+\.\d+\.\d+$
    env: JOB=deploy VERSION=$TRAVIS_TAG
    install: make install
    script: make docker-tag-push

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/
