version: '3'

services:
    db:
        # In production, you may want to use a managed database service
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=artefactguide
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password!
        volumes:
             - ./docker/db/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
