version: '3'

services:
    php:
        image: "hakindazz/artefact-guide-php:latest"
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile
        depends_on:
            - db

    api:
        image: "hakindazz/artefact-guide-api:latest"
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile.nginx
        depends_on:
            - php
        ports:
            - "8080:80"
    db:
        # In production, you may want to use a managed database service
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=artefactguide
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password!
        volumes:
             - ./docker/db/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
