version: '3'

services:
    cbag3:
        image: "c-base/cbag3:latest"
        build: .
        volumes:
            - .:/opt/cbag3:rw,cached
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        # In production, you may want to use a managed database service
        image: postgres:alpine
        environment:
            - POSTGRES_DB=artefactguide
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
             - ./docker/db/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
