version: '3'

services:
    php:
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile
        depends_on:
            - db
        # Comment out these volumes in production
        volumes:
            - ./api:/srv/api:rw,cached

    api:
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile.nginx
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./api/public:/srv/api/public:ro
    db:
        # In production, you may want to use a managed database service
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=artefactguide
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password!
        volumes:
             - ./docker/db/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
