version: '3.9'
services:
  artefactguide:
    image: ghcr.io/c-base/cbag3:dev-latest
    build:
      dockerfile: ./devops/docker/frankenphp/Dockerfile
      target: dev
    env_file: ./devops/env/dev.artefactguide.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - './app:/app'

  database:
    image: postgres:alpine
    container_name: database
    env_file: ./devops/env/dev.database.env
    ports:
      - 15432:5432
    volumes:
      - ./devops/database:/var/lib/postgresql