version: '3.9'
services:
  artefactguide:
    container_name: artefactguide
    build:
      dockerfile: ./devops/docker/php-fpm/Dockerfile
    environment:
      - APP_ENV=dev
      - APP_SECRET=3877bb09523f3a5956ea2216d99c3b9e
      - APP_DEBUG=true
    volumes:
      - '.:/var/www/html:cached'
    ports:
      - 9091:9091

  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_USER: cbag3dev
      POSTGRES_PASSWORD: cbag3dev
      POSTGRES_DB: cbag3
    ports:
      - 15432:5432