security:

    providers:
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        restricted_area:
            anonymous:      ~
            pattern:        ^/
            methods:        [POST, PUT, DELETE, PATCH]
            json_login_ldap_bind:
                provider: ~
                service: Symfony\Component\Ldap\Ldap
                check_path: /login
                username_path: _username
                password_path: _password
                query_string: '%env(LDAP_QUERY_STRING)%'
            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_USER:        ROLE_CREW
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    

    access_control:
        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: ROLE_USER }
