controllers:
    resource: ../../src/App/Controller
    type: attribute

artefactguide_controllers:
    resource: ../../src/ArtefactGuide/Application/Controller
    type: attribute

kernel:
    resource: ../../src/App/Kernel.php
    type: attribute
