services:
    cbag3.main.navbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            - {}
            - {}
            - { title: "CBAG3", titleRoute: "cbase_cbag3_base_default_index"}
            # first argument: a named array of menues:
            #- { leftmenu: @mopa_bootstrap.examplemenu=, rightmenu: @mopa_bootstrap.exampledropdown= }
            # second argument: a named array of FormType Classes
            #- { searchform: Mopa\Bundle\BootstrapSandboxBundle\Form\Type\ExampleSearchFormType }
            # third argument: a named array of options
            #- { title: "MopaBootstrapSandboxBundle", titleRoute: "mopa_bootstrap_welcome", fixedTop: true, isFluid: false }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }