services:

    cbag3.main.menu_builder:
          class: Cbase\Cbag3\BaseBundle\Navbar\MenuBuilder
          arguments: ["@knp_menu.factory"]

    cbag3.main.navbar.right:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: cbag3.main.menu_builder
        factory_method: createMainMenuRight
        arguments: ["@request", "@security.context"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: cbag3_menu_right } # The alias is what is used to retrieve the menu

    cbag3.main.navbar.left:
            class: Knp\Menu\MenuItem # the service definition requires setting the class
            factory_service: cbag3.main.menu_builder
            factory_method: createMainMenuLeft
            arguments: ["@request"]
            scope: request # needed as we have the request as a dependency here
            tags:
                - { name: knp_menu.menu, alias: cbag3_menu_left } # The alias is what is used to retrieve the menu

    cbag3.main.navbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            #- { leftmenu: @mopa_bootstrap.examplemenu=, rightmenu: @mopa_bootstrap.exampledropdown= }
            - { leftmenu: @cbag3.main.navbar.left=,rightmenu: @cbag3.main.navbar.right= }
            # second argument: a named array of FormType Classes
            #- { searchform: Mopa\Bundle\BootstrapSandboxBundle\Form\Type\ExampleSearchFormType }
            - {}
            # third argument: a named array of options
            #- { title: "MopaBootstrapSandboxBundle", titleRoute: "mopa_bootstrap_welcome", fixedTop: true, isFluid: false }
            - { title: "CBAG3", titleRoute: "cbase_cbag3_base_default_index"}
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }