imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
        name: MOCKSESSID

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine_mongodb:
    default_database: cbag3_database_test

cbase_cbag3_asset:
    upload_dir: uploads/assets_test
