imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CbaseCbag3ArtefactBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MopaBootstrapBundle, CbaseCbag3ArtefactBundle]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [ /usr/lib/node_modules, /usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: cbag3_database
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

liip_imagine:
    driver:               %imagine_driver%
#    web_root:             %kernel.root_dir%/../web
#    data_root:           %liip_imagine.web_root%
#    cache_prefix:        /media/cache
#    cache:               web_path
#    cache_clearer:       true
#    data_loader:          filesystem
#    controller_action:    liip_imagine.controller:filterAction
#    formats:              []
    filter_sets:

        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        artefact_show:
            quality: 75
            filters:
                thumbnail: { size: [700, null], mode: outbound }
        asset_show:
            quality: 75
            filters:
                thumbnail: { size: [700, null], mode: outbound }