
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

#_main:
#    resource: routing.yml

CbaseCbag3AssetBundle:
    resource: "@CbaseCbag3AssetBundle/Controller/"
    type:     annotation
    prefix:   /asset/

CbaseCbag3ArtefactBundle:
    resource: "@CbaseCbag3ArtefactBundle/Controller/"
    type:     annotation
    prefix:   /artefact/

CbaseCbag3BaseBundle:
    resource: "@CbaseCbag3BaseBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine


login:
  pattern:              /login
  defaults:             { _controller: CbaseCbag3BaseBundle:Default:login }
  requirements:
    _method:            GET

login_check:
  pattern:              /login_check

logout:
  pattern:              /logout

artefact_show_short:
    pattern:   /{slug}
    defaults:  { _controller: CbaseCbag3ArtefactBundle:Artefact:show }
