CbaseCbag3AssetBundle:
    resource: "@CbaseCbag3AssetBundle/Controller/"
    type:     annotation
    prefix:   /

CbaseCbag3ArtefactBundle:
    resource: "@CbaseCbag3ArtefactBundle/Controller/"
    type:     annotation
    prefix:   /

CbaseCbag3BaseBundle:
    resource: "@CbaseCbag3BaseBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
