# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    oauth2.authorization.url: '%env(resolve:OAUTH2_AUTHORIZATION_URL)%'
    oauth2.token.url: '%env(resolve:OAUTH2_TOKEN_URL)%'
    oauth2.profile.url: '%env(resolve:OAUTH2_USER_PROFILE_URL)%'
    oauth2.client.id: '%env(resolve:OAUTH2_CLIENT_ID)%'
    oauth2.client.secret: '%env(resolve:OAUTH2_CLIENT_SECRET)%'
    oauth2.scopes: '%env(resolve:OAUTH2_SCOPES)%'
    images.upload.directory: '%env(resolve:IMAGES_UPLOAD_DIRECTORY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $oauth2AuthorizationUrl: '%oauth2.authorization.url%'
            string $oauth2TokenUrl: '%oauth2.token.url%'
            string $oauth2ClientId: '%oauth2.client.id%'
            string $oauth2ClientSecret: '%oauth2.client.secret%'
            string $oauth2ProfileUrl: '%oauth2.profile.url%'
            string $oauth2Scopes: '%oauth2.scopes%'
            string $oauth2RedirectRoute: 'api_auth_callback'
            string $imagesUploadDirectory: '%images.upload.directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Cbase\:
        resource: '../src'
        exclude:
            - '../src/App/Kernel.php'
