services:
  # redefine the alias as it should be while making it public

  Tests\Fake\:
    resource: '../tests/Fake'

  Cbase\ArtefactGuide\Domain\ArtefactRepository: '@Tests\Fake\Infrastructure\Doctrine\InMemoryArtefactRepository'
  Cbase\ArtefactGuide\Domain\ImageRepository: '@Tests\Fake\Infrastructure\Doctrine\InMemoryImageRepository'