<?php

namespace Cbase\Cbag3\ArtefactBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Cbase\Cbag3\AssetBundle\Document\Asset;
use Doctrine\ORM\QueryBuilder;

/**
 * ArtefactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends DocumentRepository
{
    public function getByAsset(Asset $asset)
    {
        $id = $asset->getId();
        $query = $this->dm->createQueryBuilder();
        $query->field('asset.$id')->equals($id);

        return $query->getQuery()->execute();
    }

    public function getLatest($limit = 5) {
        return $this->getDocumentManager()->createQueryBuilder()
            ->find('Cbase\Cbag3\ArtefactBundle\Document\Artefact')
            ->sort('createdAt', 'desc')
            ->limit($limit)
            ->getQuery()
            ->execute();
    }

    public function getStateStats($stateName) {
        $qb =  $this->getDocumentManager()->createQueryBuilder();

        return $qb->find('Cbase\Cbag3\ArtefactBundle\Document\Artefact')
            ->field('state.'.$stateName)->equals(true)
            ->count()
            ->getQuery()
            ->execute();
    }

    public function getByDoesNotHaveThisState($stateName) {
        $qb =  $this->getDocumentManager()->createQueryBuilder();

        return $qb->find('Cbase\Cbag3\ArtefactBundle\Document\Artefact')
            ->addOr($qb->expr()->field('state.'.$stateName)->equals(false))
            ->addOr($qb->expr()->field('state.'.$stateName)->exists(false))
            ->getQuery()
            ->execute();
    }
}