<?php

namespace Cbase\Cbag3\BaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArtefactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends DocumentRepository
{
}