<?php

namespace Cbase\Cbag3\BaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Cbase\Cbag3\BaseBundle\Document\Asset;

/**
 * ArtefactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtefactRepository extends DocumentRepository
{
    public function getByAsset(Asset $asset)
    {
        $id = $asset->getId();
        $query = $this->dm->createQueryBuilder();
        $query->field('asset.$id')->equals($id);

        return $query->getQuery()->execute();
    }
}