monolog:
    handlers:
        main:
            type:  stream
            path:  "php://stdout"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            level: debug
