deptrac:
    paths:
        - ./../../../src
    layers:
        -   name: ArtefactGuideApplication
            collectors:
                -   type: className
                    regex: ArtefactGuide\\Application\\.*

    ruleset:
        ArtefactGuideApplication:
