knpu_oauth2_client:
  clients:
    # will create service: "knpu.oauth2.client.foo_bar_oauth"
    # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client
    cbase_oauth:
      type: generic
      provider_class: Cbase\Authentication\Infrastructure\OAuth2\Provider
      # optional: if your provider has custom constructor options
#      provider_options: {}

      # optional: a class that extends OAuth2Client
      client_class: Cbase\Authentication\Infrastructure\OAuth2\Client

      # now, all the normal options!
      client_id: '%env(resolve:OAUTH2_CLIENT_ID)%'
      client_secret: '%env(resolve:OAUTH2_CLIENT_SECRET)%'
      redirect_route: api_auth_callback
      redirect_params: {}
      # whether to check OAuth2 "state": defaults to true
      # use_state: true