<?php

namespace Cbase\Cbag3\AssetBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends DocumentRepository
{
}