name: CI

on: [push]

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - run: ./bin/composer selfupdate
      - run: ./bin/composer validate
      - run: ./bin/composer outdated --direct
#  phpunit:
#    steps:
#      - uses: php-actions/phpunit@v9
#        with:
#          php_version: 7.4.3
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          installComposer: 0
          phpstanVersion: ^0.12
          level: 4
          paths: src
