name: Continuous Integration

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          echo "::group::apt-get update"
          sudo apt-get update
          echo "::endgroup::"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "ctype,iconv,intl,json,xsl,sqlite3"
          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1
          php-version: "${{ matrix.php }}"
          tools: pecl

      - name: Display versions
        run: |
          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
          php -i

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          level: 4
          directories: src tests

      - name: Run tests
        run: make tests
        shell: bash
#
#      - name: Run tests
#        uses: php-actions/phpunit@v9
#        with:
#          php_version: 8.0
